### ISSUE TITLE
How to transcribe in spanish

### ISSUE THREAD

**Issue by josemgaleas** [mgonzs13/whisper_ros#1]
Hello,
I change the param "language": LaunchConfiguration("language", default="es") and the param "translate": LaunchConfiguration("translate", default=False).
The issue is that the programm doesn't transcribe well in spanish. I speak in spanish but the programm always try to translate to english.
The model that i load is the distil-large-v3 with this params:
[whisper_node-1] [INFO] Processing, 4 threads, lang = es, task = transcribe, timestamps = 1 
Thank you

**Comment by mgonzs13** [comment]
Hey @josemgaleas, sorry for the delay. The problem is that you are using the distil version. Check this [issue](https://huggingface.co/distil-whisper/distil-large-v3/discussions/2) from the Hugging Face distil whisper repo. To solve it, you can use a Spanish model or the [original model](https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-large-v3-q5_0.bin).
